### ISSUE TITLE
Column for emoji name

### ISSUE THREAD

**Issue by Temetz** [emoji-status-consortium/emoji-status-spec#2]
I think it would be good to have a column for the official unicode emoji name. This would help to identify emojis easily. 

If emoji name is considered as too much, maybe the spec should include the emoji code, for example `U+1F60A`

**Comment by melonmanchan** [comment]
This one seems like a good idea. Maybe a link to the emojipedia article too?

**Comment by Temetz** [comment]
I think that just to code or description is enough. If people are interested in more detailed explanations about a particular emoji they may just as well Google it.

**Comment by bqqbarbhg** [comment]
I would suggest using both official Unicode name _and_ code point in parentheses.

For example: :joy: FACE WITH TEARS OF JOY (U+1F602)

**Comment by melonmanchan** [comment]
Lähetetty Samsung Mobilesta.

<div>-------- Alkuperäinen viesti --------</div><div>Lähettäjä: Samuli <notifications@github.com> </div><div>Päivämäärä:04.21.2016  13.48  (GMT+02:00) </div><div>Saaja: emoji-status-consortium/emoji-status-spec <emoji-status-spec@noreply.github.com> </div><div>Kopio: Matti Jokitulppo <melonmanchan@gmail.com>, Comment <comment@noreply.github.com> </div><div>Aihe: Re: [emoji-status-consortium/emoji-status-spec] Column for emoji name
  (#2) </div><div>
</div>I would say both official Unicode name and code point in parentheses.

For example:  FACE WITH TEARS OF JOY (U+1F602)

**Comment by Temetz** [comment]
Implemented in: https://github.com/emoji-status-consortium/emoji-status-spec/commit/37f3c088aa979456b92007ced9fe28fb5ae2c064
